In [ ]:
import zarr
import numpy as np
from pathlib import Path
from funlib.persistence import open_ds

zarr_path = Path(r"S:\[PROJ]_DCIS\PathOrchestra\TEMP_test_inference\2015003_H&E.zarr")
save_path = Path(r"S:\[PROJ]_DCIS\PathOrchestra\TEMP_test_inference\2015003_H&E_pred.zarr")

# load input image
s2_array = open_ds(zarr_path / "raw" / "s1")

# load output mask
store = zarr.DirectoryStore(str(save_path))
z = zarr.open(store, mode="r")

print("=== INPUT IMAGE ===")
print(f"  shape:      {s2_array.shape}")
print(f"  voxel_size: {s2_array.voxel_size}")
print(f"  roi:        {s2_array.roi}")
print(f"  offset:     {s2_array.offset}")

print("\n=== OUTPUT MASK ===")
print(f"  shape:      {z.shape}")
print(f"  chunks:     {z.chunks}")

print("\n=== NAPARI SCALE ===")
print(f"  image scale used: [1, 1]")
print(f"  mask scale used:  [4, 4]")
print(f"  expected mask shape if aligned: {s2_array.shape[:2]}")

=== INPUT IMAGE ===
  shape:      (37531, 34860, 3)
  voxel_size: (504, 504)
  roi:        [0:18915624, 0:17569440] (18915624, 17569440)
  offset:     (0, 0)

=== OUTPUT MASK ===
  shape:      (37531, 34860)
  chunks:     (1173, 2179)

=== NAPARI SCALE ===
  image scale used: [1, 1]
  mask scale used:  [4, 4]
  expected mask shape if aligned: (37531, 34860)


In [14]:
import torch

ckpt = torch.load(r"E:\[PROJ]_DCIS\Decoder_training\05112026_classes-remapped\best_model.pth", map_location="cpu")

# check what's in the checkpoint
print("Keys in checkpoint:", list(ckpt.keys())[:10])

# check decoder head weights - should NOT be near zero if trained
head_weight = ckpt["decoder.head.weight"]
print(f"\ndecoder.head.weight shape: {head_weight.shape}")
print(f"decoder.head.weight mean:  {head_weight.mean().item():.6f}")
print(f"decoder.head.weight std:   {head_weight.std().item():.6f}")

# compare to what random init looks like
# random init from kaiming_uniform typically has std ~ 0.1-0.3
# a trained model should have different statistics
print(f"\ndecoder.bottleneck.block.0.weight std: {ckpt['decoder.bottleneck.block.0.weight'].std().item():.6f}")

C:\Users\Waluigi\AppData\Local\Temp\ipykernel_21872\3233639377.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(r"E:\[PROJ]_DCIS\Decoder_training\051120

Keys in checkpoint: ['encoder.vit.cls_token', 'encoder.vit.pos_embed', 'encoder.vit.patch_embed.proj.weight', 'encoder.vit.patch_embed.proj.bias', 'encoder.vit.blocks.0.norm1.weight', 'encoder.vit.blocks.0.norm1.bias', 'encoder.vit.blocks.0.attn.qkv.weight', 'encoder.vit.blocks.0.attn.qkv.bias', 'encoder.vit.blocks.0.attn.proj.weight', 'encoder.vit.blocks.0.attn.proj.bias']

decoder.head.weight shape: torch.Size([4, 64, 1, 1])
decoder.head.weight mean:  -0.105984
decoder.head.weight std:   0.363517

decoder.bottleneck.block.0.weight std: 0.085340


In [13]:
import torch

ckpt = torch.load(r"E:\[PROJ]_DCIS\Decoder_training\05122026_incomplete-run\best_model.pth", map_location="cpu")

# check what's in the checkpoint
print("Keys in checkpoint:", list(ckpt.keys())[:10])

# check decoder head weights - should NOT be near zero if trained
head_weight = ckpt["decoder.head.weight"]
print(f"\ndecoder.head.weight shape: {head_weight.shape}")
print(f"decoder.head.weight mean:  {head_weight.mean().item():.6f}")
print(f"decoder.head.weight std:   {head_weight.std().item():.6f}")

# compare to what random init looks like
# random init from kaiming_uniform typically has std ~ 0.1-0.3
# a trained model should have different statistics
print(f"\ndecoder.bottleneck.block.0.weight std: {ckpt['decoder.bottleneck.block.0.weight'].std().item():.6f}")

C:\Users\Waluigi\AppData\Local\Temp\ipykernel_21872\3044127927.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(r"E:\[PROJ]_DCIS\Decoder_training\051220

Keys in checkpoint: ['encoder.vit.cls_token', 'encoder.vit.pos_embed', 'encoder.vit.patch_embed.proj.weight', 'encoder.vit.patch_embed.proj.bias', 'encoder.vit.blocks.0.norm1.weight', 'encoder.vit.blocks.0.norm1.bias', 'encoder.vit.blocks.0.attn.qkv.weight', 'encoder.vit.blocks.0.attn.qkv.bias', 'encoder.vit.blocks.0.attn.proj.weight', 'encoder.vit.blocks.0.attn.proj.bias']

decoder.head.weight shape: torch.Size([4, 64, 1, 1])
decoder.head.weight mean:  -0.087784
decoder.head.weight std:   0.360250

decoder.bottleneck.block.0.weight std: 0.095464


In [11]:
import torch

ckpt = torch.load(r"E:\[PROJ]_DCIS\Decoder_training\best_model.pth\best_model.pth", map_location="cpu")

# check what's in the checkpoint
print("Keys in checkpoint:", list(ckpt.keys())[:10])

# check decoder head weights - should NOT be near zero if trained
head_weight = ckpt["decoder.head.weight"]
print(f"\ndecoder.head.weight shape: {head_weight.shape}")
print(f"decoder.head.weight mean:  {head_weight.mean().item():.6f}")
print(f"decoder.head.weight std:   {head_weight.std().item():.6f}")

# compare to what random init looks like
# random init from kaiming_uniform typically has std ~ 0.1-0.3
# a trained model should have different statistics
print(f"\ndecoder.bottleneck.block.0.weight std: {ckpt['decoder.bottleneck.block.0.weight'].std().item():.6f}")

C:\Users\Waluigi\AppData\Local\Temp\ipykernel_21872\2845709130.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(r"E:\[PROJ]_DCIS\Decoder_training\best_m

Keys in checkpoint: ['encoder.vit.cls_token', 'encoder.vit.pos_embed', 'encoder.vit.patch_embed.proj.weight', 'encoder.vit.patch_embed.proj.bias', 'encoder.vit.blocks.0.norm1.weight', 'encoder.vit.blocks.0.norm1.bias', 'encoder.vit.blocks.0.attn.qkv.weight', 'encoder.vit.blocks.0.attn.qkv.bias', 'encoder.vit.blocks.0.attn.proj.weight', 'encoder.vit.blocks.0.attn.proj.bias']

decoder.head.weight shape: torch.Size([4, 64, 1, 1])
decoder.head.weight mean:  -0.110585
decoder.head.weight std:   0.366459

decoder.bottleneck.block.0.weight std: 0.128281


In [2]:
import json
import numpy as np

with open(r"E:\[PROJ]_DCIS\PathOrchestra\TEMP_test_inference\logit_log.json") as f:
    log = json.load(f)

logits = np.array(list(log.values()))
print(f"Num blocks logged: {len(logits)}")
print(f"Std:               {logits.std(axis=0)}")

winners = np.argmax(logits, axis=1)
for c in range(4):
    print(f"Class {c} wins: {(winners == c).sum()} / {len(logits)} blocks")

Num blocks logged: 6391
Std:               [0.00325256 0.00191762 0.00455099 0.00501447]
Class 0 wins: 6391 / 6391 blocks
Class 1 wins: 0 / 6391 blocks
Class 2 wins: 0 / 6391 blocks
Class 3 wins: 0 / 6391 blocks


In [3]:
import json
import numpy as np

with open(r"E:\[PROJ]_DCIS\PathOrchestra\TEMP_test_inference\logit_log_less-background.json") as f:
    log = json.load(f)

logits = np.array(list(log.values()))
print(f"Num blocks logged: {len(logits)}")
print(f"Std:               {logits.std(axis=0)}")

winners = np.argmax(logits, axis=1)
for c in range(3):
    print(f"Class {c} wins: {(winners == c).sum()} / {len(logits)} blocks")

Num blocks logged: 6391
Std:               [3.7960965  1.91842786 2.93309087 2.0084386 ]
Class 0 wins: 6317 / 6391 blocks
Class 1 wins: 0 / 6391 blocks
Class 2 wins: 0 / 6391 blocks


In [ ]:
import json
import numpy as np

with open(r"E:\[PROJ]_DCIS\PathOrchestra\TEMP_test_inference\logit_log.json") as f:
    log = json.load(f)

logits = np.array(list(log.values()))  # (25885, 4)

# show the actual logit values for the top 10 blocks where class 0 wins
class0_wins = logits[np.argmax(logits, axis=1) == 0]
print("Sample logits where class 0 wins:")
print(class0_wins[:5])

# show the 18 blocks where class 3 wins
class3_wins = logits[np.argmax(logits, axis=1) == 3]
print("\nLogits where class 3 wins:")
print(class3_wins)

# overall logit means per class
print(f"\nOverall mean per class: {logits.mean(axis=0)}")

Sample logits where class 0 wins:
[[ 60.95574951 -66.15665436 -37.39506531 -34.25962067]
 [ 60.83583069 -68.70409393 -28.98170853 -43.16753006]
 [ 60.99151993 -70.23137665 -25.05699158 -47.56954575]
 [ 60.29908752 -69.42344666 -25.63391876 -46.10138321]
 [ 61.04136276 -70.44332886 -24.76306915 -47.9519577 ]]

Logits where class 3 wins:
[[  2.14713407 -12.10304165  -7.22653103   3.75980878]
 [  3.04697251 -12.65697193  -8.11566353   3.34977579]
 [  2.54016018 -12.38866711  -7.92441416   3.68444371]
 [  3.02113175 -12.98292255  -8.33638      3.52401185]
 [  1.67109179 -11.76247597  -7.50998735   4.27007532]
 [  2.04203677 -11.8512125   -7.78459692   4.0192256 ]
 [  3.17971945 -13.04099941  -8.48003101   3.45692778]
 [  2.51440358 -12.34965992  -8.24625587   3.85598063]
 [  1.95020652 -12.06388092  -8.01644897   4.27682257]
 [  2.3091104  -12.25443172  -7.58398914   3.78670597]
 [  3.39256215 -12.80347919  -8.90598297   3.39490676]
 [  2.72945976 -12.74839878  -7.85595798   3.55918741]
 [

In [9]:
import numpy as np
from pathlib import Path
from collections import Counter

data_root = Path(r"E:\[PROJ]_DCIS\DATA\training_patches\annotation_scheme-0\as0_all_tiles")
files = sorted(data_root.glob("*.npz"))

all_pixels = Counter()

for f in files:
    data = np.load(f)
    mask = data['label']
    vals, counts = np.unique(mask, return_counts=True)
    for v, c in zip(vals, counts):
        all_pixels[int(v)] += int(c)

total = sum(all_pixels.values())
print(f"Total files: {len(files)}")
print(f"Total pixels: {total:,}")
print(f"\nClass distribution:")
for k, v in sorted(all_pixels.items()):
    print(f"  class {k:4d}: {v:12,} pixels  ({100*v/total:.2f}%)")

Total files: 11562
Total pixels: 580,134,912

Class distribution:
  class    0:  306,508,222 pixels  (52.83%)
  class    1:   17,106,765 pixels  (2.95%)
  class    2:   53,085,776 pixels  (9.15%)
  class    3:    6,489,088 pixels  (1.12%)
  class  255:  196,945,061 pixels  (33.95%)


In [1]:
import numpy as np
from pathlib import Path
from collections import Counter

data_root = Path(r"E:\[PROJ]_DCIS\DATA\training_patches\annotation_scheme-0\as0_tissue-tiles")
files = sorted(data_root.glob("*.npz"))

all_values = Counter()
files_with_unexpected = []

for f in files:
    data = np.load(f)
    mask = data['label']
    unique_vals = np.unique(mask)
    
    # flag any file with values outside expected set {0, 1, 2, 3, 255}
    expected = {0, 1, 2, 3, 255}
    unexpected = set(unique_vals.tolist()) - expected
    if unexpected:
        files_with_unexpected.append((f.name, unexpected))
    
    for v, c in zip(*np.unique(mask, return_counts=True)):
        all_values[int(v)] += int(c)

print("=== GLOBAL CLASS DISTRIBUTION ===")
total = sum(all_values.values())
for k, v in sorted(all_values.items()):
    print(f"  class {k:4d}: {v:12,} pixels  ({100*v/total:.2f}%)")

print(f"\n=== UNEXPECTED VALUES ===")
if files_with_unexpected:
    for fname, vals in files_with_unexpected[:10]:
        print(f"  {fname}: {vals}")
    print(f"  ... {len(files_with_unexpected)} files total with unexpected values")
else:
    print("  None — all values are in {0, 1, 2, 3, 255}")

=== GLOBAL CLASS DISTRIBUTION ===
  class    1:   17,106,765 pixels  (6.79%)
  class    2:   53,085,776 pixels  (21.06%)
  class    3:    6,489,088 pixels  (2.57%)
  class  255:  175,402,595 pixels  (69.58%)

=== UNEXPECTED VALUES ===
  None — all values are in {0, 1, 2, 3, 255}


In [10]:
import numpy as np

# your pixel counts
counts = np.array([
     22_603_945,   # class 0 - background
     17_106_765,   # class 1 - epithelium
     53_085_776,   # class 2 - stroma
      6_489_088,   # class 3 - other
])

# inverse frequency weighting
weights = 1.0 / counts
weights = weights / weights.sum()  # normalize to sum to 1
weights = weights * len(counts)    # scale so mean weight = 1

print("Class weights:")
for i, w in enumerate(weights):
    print(f"  class {i}: {w:.4f}")

Class weights:
  class 0: 0.6420
  class 1: 0.8483
  class 2: 0.2734
  class 3: 2.2363


In [4]:
# instead of inverse frequency, try inverse frequency squared
counts = np.array([306_508_222, 17_106_765, 53_085_776, 6_489_088])
weights = 1.0 / (counts ** 0.5)  # square root instead of linear
weights = weights / weights.sum() * 4
print(weights)

[0.27570045 1.16701005 0.66247494 1.89481455]


In [1]:
import json
import numpy as np

with open(r"E:\[PROJ]_DCIS\PathOrchestra\TEMP_test_inference\logit_log_less-background.json") as f:
    log = json.load(f)

logits = np.array(list(log.values()))

print(f"Mean logits per class: {logits.mean(axis=0)}")
print(f"Std  logits per class: {logits.std(axis=0)}")
print(f"\nSample logits (first 5):\n{logits[:5]}")

winners = np.argmax(logits, axis=1)
class3 = logits[winners == 3]
class0 = logits[winners == 0]

print(f"\nClass 0 winning blocks — mean: {class0.mean(axis=0)}")
print(f"Class 3 winning blocks — mean: {class3.mean(axis=0)}")

Mean logits per class: [ 12.85841971 -12.73745654 -15.25893857  -7.64087476]
Std  logits per class: [3.7960965  1.91842786 2.93309087 2.0084386 ]

Sample logits (first 5):
[[ 14.19785786 -13.50850964 -16.58710289  -8.46637821]
 [ 13.88876629 -13.24555492 -16.1309967   -8.22555447]
 [ 13.97930622 -13.32734013 -16.27776909  -8.30038357]
 [ 13.87304783 -13.24086285 -16.11138916  -8.21198082]
 [ 14.00244141 -13.33237839 -16.31612015  -8.32836819]]

Class 0 winning blocks — mean: [ 13.15698601 -12.83550851 -15.36389827  -7.7791585 ]
Class 3 winning blocks — mean: [-12.62865268  -4.36726316  -6.29906794   4.16369833]
